name: Auto Click

on:
  schedule:
    - cron: '55 1 * * 1-5'  # 星期一 ~ 五早上 09:55 (UTC+8) 執行一次
    - cron: '20 11 * * 1-5'  # 星期一 ~ 五下午 7:20 (UTC+8) 執行一次
  workflow_dispatch:

jobs:
  run-script:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: '3.0'  # 確保這裡的版本與你的開發環境一致

    # - name: Install dependencies
    #   run: |
    #     gem install selenium-webdriver headless
    #     gem install json

    - name: Run auto_click script
      env:
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        BIPOID: ${{ secrets.BIPOID }}
        BIPOPASSWORD: ${{ secrets.BIPOPASSWORD }}
      run: |
        ruby auto_click.rb 